### ISSUE TITLE
Make MenuItem Customizable 

### ISSUE THREAD

**Issue by mario-aleo** [likern/react-native-enhanced-popup-menu#4]
I like this library, my only issue here is that I can't use other things beside string as MenuItem children, It would be nice to be able to use a View with other things inside of it.

**Comment by likern** [comment]
Good catch. Have no exact plans. But I am going to add more UI customizations.

**Comment by marlon-wiprud** [comment]
+1

**Comment by likern** [comment]
Fixed in https://www.npmjs.com/package/@breeffy/react-native-popup-menu/v/0.7.1-dev.0

Now there is MenuItemText and MenuItemView components available.
If there is bugs - please open them here https://github.com/breeffy/react-native-popup-menu/issues
