### ISSUE TITLE
MenuItem's text "jumps" at the start

### ISSUE THREAD

**Issue by abikbulatov** [likern/react-native-enhanced-popup-menu#5]
Hello, I've faced a problem: when a menu shows up text jumps a little at the very beginning and it looks ugly on real devices, ([here's a demo that shows this visual bug, decrease speed to 0.5](https://www.youtube.com/watch?v=qx9xE6sqO-A&feature=youtu.be)). The `MenuItem` is very simple, it has string variable and vector icon. 

Although, the glitch disappears when I remove either string or icon from MenuItem ([demo](https://www.youtube.com/watch?v=5f8kti2RWVc&feature=youtu.be)).

Code of the menu if it helps:
` _mainMenu = () => (<Menu
        ref={(ref) => this.menuRef = ref}
        style={styles.menuStyles}
    >
        <MenuItem
            textStyle={styles.menuTextStyles}
            underlayColor={'#2C2B30'}
            onPress={() => {
                this.props.editMessage(this.props.message);
                this._hideMenu(this.menuRef);
            }}>
            {strings.edit}
            <SvgEditMessage />
        </MenuItem>
        <MenuDivider color={'#676570'}/>
        <MenuItem
            textStyle={styles.menuTextStyles}
            underlayColor={'#2C2B30'}
            onPress={() => {
                this._hideMenu(this.menuRef);
                this._showMenu(this.deletionMenuRef, this.messageRef);
            }}>
            {strings.delete}
            <SvgTrashIcon/>
        </MenuItem>
    </Menu>);`

**Comment by likern** [comment]
@xKRUTOIx Could you provide simple app, which reproduces this issue? So I can run it and start debugging right away.

Something minimalistict, app with screen with one button, on tap on this button menu is showed up.

**Comment by abikbulatov** [comment]
@likern Thanks for the answer.
[Simple app snack code ](https://snack.expo.io/@xkrutoix/testmenu)

**Comment by likern** [comment]
@xKRUTOIx I have not touched that part of code from original project https://github.com/mxck/react-native-material-menu. It looks like only **Text** is supported for **MenuItem**.

That's what I found on original page:
> **Children** must be based on `<Text>` component (like text itself, strings, react-native-vector-icons or > expo icons) otherwise you may get an error on a real device

**MenuItem** is just a something rendered within a **Text** component:
```
<TouchableHighlight
      {...props}
      disabled={disabled}
      onPress={onPress}
      style={[styles.container, style]}
      underlayColor={underlayColor}
    >
      <Text
        ellipsizeMode={Platform.OS === 'ios' ? 'clip' : 'tail'}
        numberOfLines={1}
        style={[
          styles.title,
          disabled && { color: disabledTextColor },
          textStyle,
        ]}
      >
        {children}
      </Text>
    </TouchableHighlight>
```

I don't think (haven't work with **react-native-svg** extensively) it is **legible** to put svg inside text.

**Comment by likern** [comment]
My suggestion is for now do not consider **MenuItem** as a required element. Just copy paste it, modify as you want and use instead of MenuItem.

**Comment by abikbulatov** [comment]
Ohh...I see, maybe it's better to ask in the original project then.

Although I've found [this issue](https://github.com/mxck/react-native-material-menu/issues/42) where the original project's author said that MenuItem treats vector icons as text, I've tried vector icon instead **svg** and I had the same glitch : (

Anyway, thanks for the answers!

**Comment by likern** [comment]
@xKRUTOIx It's more about how `<Text />` is working in React Native. I think it doesn't work good with nesting other elements inside `<Text />` like was pointed out in these bugs: https://github.com/facebook/react-native/issues/25197, https://github.com/facebook/react-native/issues/18826

You can inject string or other Text elements inside Text: 
```
<Text style={styles.baseText}>
  <Text style={styles.titleText} onPress={this.onPressTitle}>
    {this.state.titleText + '\n\n'}
  </Text>
  <Text numberOfLines={5}>
    {this.state.bodyText}
  </Text>
</Text>
```

And https://github.com/oblador/react-native-vector-icons components are just standard Text - that's why they are working inside Text. https://github.com/react-native-community/react-native-svg is a native component, implementing SVG. It doesn't based on React Native `Text` component. 

I think you can ask question in react-native-svg about putting SVG inside Text.

**Comment by abikbulatov** [comment]
@likern You were right. I managed to solve this problem, I just used my custom component instead of `MenuItem`. Looks like you can close this issue.
Thanks a lot!
