### ISSUE TITLE
Large menus are not displayed correctly on small devices

### ISSUE THREAD

**Issue by nuevoleonkx** [likern/react-native-enhanced-popup-menu#6]
Becase height is calculated, menu is not displayed correctly even if we use computeOffset option. Would be great to reduce the height and add a scrollview if options doesn't fit.

**Comment by likern** [comment]
What do you mean by "not displayed correctly"? Could you provide screenshots?

As far as I remember, menu expands to contain its elements.

**Comment by nuevoleonkx** [comment]
![image](https://user-images.githubusercontent.com/31934700/72943162-eb1a7a80-3d3a-11ea-9265-5dace6df53fa.png)

because is a small screen (iphone 5S landscape). The popup menú is displayed in wrong position. No matter if a stackTo Position flag is given.

btw.. the rest of the items are hidden on the top (6 in total)

**Comment by likern** [comment]
Ok, looks like I understand. Are you trying to render a big popup, which is bigger than one screen dimension? And in that case you want to see scrolling?

**Comment by nuevoleonkx** [comment]
Yes. I added a ScrollView to enclose MenuItems. However the important thing is how to reduce the height of its parent Menu? Thanks

**Comment by likern** [comment]
ScrollView should work. You set up desired visible height of ScrollView. Menu will be expanded accordingly.
